/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package responsables;

import activosfijos.ModelosTabla;
import areas.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import productos.Producto;
import saldos.DatosSaldosini;

/**
 *
 * @author OSPINO Y ASOCIADO
 */
public class GrillaResponsable extends javax.swing.JDialog {

    Object poder;
    ModelosTabla tm;
    private int quienPide;

    /**
     * Creates new form GrillaArea
     */
    public GrillaResponsable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        String[] columnas = {"indiceRe","idresponsable", "nombrerespon", "codedireccion", "namedireccion", "codearea", "namearea", "codedepartamento", "namedepartamento"};
        this.tm = new ModelosTabla(columnas, jTable1, "responsables");
        jTable1.setModel(tm);
        
    }

    public void center() {
        int sw = 0;
        tm.vaciarTabla();
        try {
            ResultSet resultado1 = Producto.c.MysqlConsulta("select indiceRe,idresponsable,nombrerespon,codedireccion,namedireccion,codearea,namearea,codedepartamento,namedepartamento from responsables where  nombrerespon like'%" + jTextField1.getText() + "%'");

            while (resultado1.next()) // va avanzando de UN(1) cliente.
            {
                String[] columnas = {resultado1.getString("indiceRe"),resultado1.getString("idresponsable"), resultado1.getString("nombrerespon"), resultado1.getString("codedireccion"), resultado1.getString("namedireccion"), resultado1.getString("codearea"), resultado1.getString("namearea"), resultado1.getString("codedepartamento"), resultado1.getString("namedepartamento")};
                tm.ingresarUsuario(columnas);
                sw = 1;
            }
            if (sw == 0) {
                JOptionPane.showMessageDialog(this, "NO existe el Responsable");

            }
            resultado1.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error al buscar los datos" + e);
        }
    }

    public void thesecretsoul() {
        int selectedRow = jTable1.getSelectedRow();
        DatosSaldosini get = (DatosSaldosini) ClasArea.are.get("activo");
        if(valide(jTable1.getValueAt(selectedRow, 0).toString())){
        get.odtenerDatoR(jTable1.getValueAt(selectedRow, 0).toString());
        DatosSaldosini.jTextField6.setText(jTable1.getValueAt(selectedRow, 1).toString());
        DatosSaldosini.jLabel4.setText(jTable1.getValueAt(selectedRow, 2).toString());
        DatosSaldosini.jLabel7.setText(jTable1.getValueAt(selectedRow, 3).toString());
        DatosSaldosini.jLabel6.setText(jTable1.getValueAt(selectedRow, 4).toString());
        DatosSaldosini.jLabel2.setText(jTable1.getValueAt(selectedRow, 5).toString());
        DatosSaldosini.jLabel10.setText(jTable1.getValueAt(selectedRow, 6).toString());
        DatosSaldosini.jLabel3.setText(jTable1.getValueAt(selectedRow, 7).toString());
        DatosSaldosini.jLabel5.setText(jTable1.getValueAt(selectedRow, 8).toString());
        get.habilitarInsertare();
        }
    }
    
    public boolean valide(String string) {
        try {
            ResultSet MysqlConsulta = Producto.c.MysqlConsulta("SELECT * FROM  `encabezadosaldoactivvo` WHERE  `indiceRe` LIKE  '"+string+"'");
            if(MysqlConsulta.next()){
                JOptionPane.showMessageDialog(rootPane, "ya existe");
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrillaResponsable.class.getName()).log(Level.SEVERE, null, ex);
            return true;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jTextField1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jSeparator21 = new javax.swing.JToolBar.Separator();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        jSeparator22 = new javax.swing.JToolBar.Separator();
        jSeparator24 = new javax.swing.JToolBar.Separator();
        jSeparator23 = new javax.swing.JToolBar.Separator();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jButton2.setText("Nuevo");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Actualizar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator1);

        jButton4.setText("Borrar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);

        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jToolBar1.add(jTextField1);
        jToolBar1.add(jSeparator7);
        jToolBar1.add(jSeparator10);
        jToolBar1.add(jSeparator12);
        jToolBar1.add(jSeparator11);
        jToolBar1.add(jSeparator14);
        jToolBar1.add(jSeparator15);
        jToolBar1.add(jSeparator17);
        jToolBar1.add(jSeparator16);
        jToolBar1.add(jSeparator18);
        jToolBar1.add(jSeparator21);
        jToolBar1.add(jSeparator20);
        jToolBar1.add(jSeparator22);
        jToolBar1.add(jSeparator24);
        jToolBar1.add(jSeparator23);
        jToolBar1.add(jSeparator19);
        jToolBar1.add(jSeparator13);
        jToolBar1.add(jSeparator8);
        jToolBar1.add(jSeparator9);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator6);

        jButton6.setText("Salir");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try {
            int selectedRow = jTable1.getSelectedRow();
             RegistrosResponsables get = (RegistrosResponsables) ClasArea.are.get("respons");
            ResultSet resultado1 = Producto.c.MysqlConsulta("select * from responsables  where idresponsable='" + jTable1.getValueAt(selectedRow, 1).toString() + "'");
            if (resultado1.next()) {
               get.deedfulcode(resultado1.getString("idresponsable"));
               get.deefaulname(resultado1.getString("nombrerespon"));
               get.deefuljcomb4(resultado1.getString("estado"));
               get.deefuljcom1(resultado1.getString("encargago"));
               get.deefuljcom2(resultado1.getString("cargo_egerce"));
               get.deefuljt2(resultado1.getString("codedireccion"));
               get.deefuljl1(resultado1.getString("namedireccion"));
               get.deefuljtf4(resultado1.getString("codearea"));
               get.deefuljl2(resultado1.getString("namearea"));
               get.deefuljtf5(resultado1.getString("codedepartamento"));
               get.deefuljl3(resultado1.getString("namedepartamento"));
               get.deefuljtf6(resultado1.getString("codecentrodecosto"));
               get.deefuljl4(resultado1.getString("namecentrodecosto"));
                this.poder = ClasArea.are.get("respons");
               JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Error almenos seleleccione un campo en la tabla");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.poder = ClasArea.are.get("respons");
               JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            if(quienPide==1){
                thesecretsoul();
            }
            if(quienPide==2){
                mandarTraslate1();
            }
            if(quienPide==3){
                mandarTraslate2();
            }
            setVisible(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        center();
    }//GEN-LAST:event_jTextField1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrillaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrillaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrillaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrillaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GrillaResponsable dialog = new GrillaResponsable(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator21;
    private javax.swing.JToolBar.Separator jSeparator22;
    private javax.swing.JToolBar.Separator jSeparator23;
    private javax.swing.JToolBar.Separator jSeparator24;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
void refrescarGrilla1(String[] s) {
        try {
            this.tm.actualizarUsuario(s, jTable1.getSelectedRow());
        } catch (Exception e) {
            this.tm.actualizarUsuario(s, tm.getRowCount() - 1);
        }
    }

    void refrescarGrilla(String[] m) {
        this.tm.ingresarUsuario(m);
    }

    /*
    con este metodo yo le digo quien lo esta llamando
    
    si yo le paso como parametro 1 el que le esta pidiendo datos es saldos iniciales
    
    si yo le paso como parametro 2 el que le esta pidiendo datos es trasladoActivo 
    Nota: en este caso es id responsable a enviar
    
    si yo le paso como parametro 3 el que le esta pidiendo datos es trasladoActivo 
    Nota: en este caso es id responsable que recibe
    */
    public void quienPide(int cd) {
        this.quienPide=cd;
    }

    private void mandarTraslate1() {
        int selectedRow = jTable1.getSelectedRow();
        traslados.TrasladodeAtivo get = (traslados.TrasladodeAtivo) ClasArea.are.get("trasladoact");        
        get.setjTextField1(jTable1.getValueAt(selectedRow, 1).toString(),jTable1.getValueAt(selectedRow, 0).toString());
    }

    private void mandarTraslate2() {
        int selectedRow = jTable1.getSelectedRow();
        traslados.TrasladodeAtivo get = (traslados.TrasladodeAtivo) ClasArea.are.get("trasladoact");           
        get.setjTextField3(jTable1.getValueAt(selectedRow, 1).toString(),jTable1.getValueAt(selectedRow, 0).toString());     
    }
}
