/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package responsables;

import areas.ClasArea;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import menuactivofijo.ValidarCamposVacios;
import productos.Producto;
import saldos.DatosSaldosini;

/**
 *
 * @author OSPINO Y ASOCIADO
 */
public class RegistrosResponsables extends javax.swing.JDialog {
ValidarCamposVacios va;
 Object poder;
    /**
     * Creates new form RegistrosResponsables
     */
    public RegistrosResponsables(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Component[] c={code,name};
        this.va=new ValidarCamposVacios(c);
    }
    void mayuscula(){
        name.setText(name.getText().toUpperCase());
    }
     public void center() {
       
      
        try {
            ResultSet resultado1 = Producto.c.MysqlConsulta("select indiceRe from responsables where  idresponsable='" + code.getText() + "'");

            while (resultado1.next()) // va avanzando de UN(1) cliente.
            {
              jLabel6.setText(resultado1.getString("indiceRe"));
            }
            resultado1.close();
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "error al buscar los datos" + e);
        }
    }
public void guardar() {
        try {   
           Producto.c.EjecutarMysql("INSERT INTO `atcivofijo`.`responsables` (`idresponsable`, `nombrerespon`, `estado`, `encargago`, `cargo_egerce`, `codedireccion`, `namedireccion`, `codearea`, `namearea`, `codedepartamento`, `namedepartamento`, `codecentrodecosto`, `namecentrodecosto`) VALUES ('" +code.getText() + "','" + name.getText() +"','" + jComboBox4.getSelectedItem()+"','" + jComboBox1.getSelectedItem()+"','" + jComboBox2.getSelectedItem()+"','" +jTextField2.getText() +"','" +jLabel1.getText() +"','" +jTextField4.getText() +"','" +jLabel2.getText() +"','" +jTextField4.getText() +"','" +jLabel3.getText() +"','" +jTextField6.getText() +"','" +jLabel4.getText() +"')");
           center();
           GrillaResponsable get = (GrillaResponsable) ClasArea.are.get("grillarepons");
            String s[]={jLabel6.getText(),code.getText(),name.getText(),jTextField2.getText(),jLabel1.getText(),jTextField4.getText(),jLabel2.getText(),jTextField4.getText(),jLabel3.getText()};
            get.refrescarGrilla(s);
            JOptionPane.showMessageDialog(this, " insertado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e);
        }
    }
public void update() {
//        ProcedimientoSelec catius = (ProcedimientoSelec) Procedimientos.procedimiento.get("procedimientoSelectivo");
        try {
            Producto.c.EjecutarMysql("update producto set nombrerespon='" + name.getText()+"' where idresponsable='" + code.getText() + "'");
            JOptionPane.showMessageDialog(this, " SUS DATOS FUERON GUARDADOS CORREPTAMENTE");
            center();
            String m[]={jLabel6.getText(),code.getText(),name.getText(),jTextField2.getText(),jLabel1.getText(),jTextField4.getText(),jLabel2.getText(),jTextField4.getText(),jLabel3.getText()};
            GrillaResponsable y = (GrillaResponsable) ClasArea.are.get("grillaproduc");
            y.refrescarGrilla1(m);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton6 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        jSeparator22 = new javax.swing.JToolBar.Separator();
        jSeparator21 = new javax.swing.JToolBar.Separator();
        jSeparator25 = new javax.swing.JToolBar.Separator();
        jSeparator26 = new javax.swing.JToolBar.Separator();
        jSeparator27 = new javax.swing.JToolBar.Separator();
        jSeparator23 = new javax.swing.JToolBar.Separator();
        jSeparator24 = new javax.swing.JToolBar.Separator();
        jSeparator35 = new javax.swing.JToolBar.Separator();
        jSeparator34 = new javax.swing.JToolBar.Separator();
        jSeparator28 = new javax.swing.JToolBar.Separator();
        jSeparator30 = new javax.swing.JToolBar.Separator();
        jSeparator31 = new javax.swing.JToolBar.Separator();
        jSeparator32 = new javax.swing.JToolBar.Separator();
        jSeparator33 = new javax.swing.JToolBar.Separator();
        jSeparator29 = new javax.swing.JToolBar.Separator();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del Responsable"));
        name.setName("Nombre del Responsable"); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 420, 40));

        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion:"));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 40));

        code.setBorder(javax.swing.BorderFactory.createTitledBorder("ID del Responsable"));
        code.setName("ID del Responsable"); // NOI18N
        jPanel1.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 330, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BUSCAR 1OK.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 80, 30));

        jTextField4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder("Area:"));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 330, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BUSCAR 1OK.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 80, 30));

        jTextField5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamento:"));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 330, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BUSCAR 1OK.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 80, 30));

        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder("Centro de Costo:"));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 330, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BUSCAR 1OK.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 80, 30));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardaruni.jpg"))); // NOI18N
        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator6);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udapte.jpg"))); // NOI18N
        jButton7.setText("Actualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator10);
        jToolBar1.add(jSeparator9);
        jToolBar1.add(jSeparator8);
        jToolBar1.add(jSeparator11);
        jToolBar1.add(jSeparator15);
        jToolBar1.add(jSeparator18);
        jToolBar1.add(jSeparator16);
        jToolBar1.add(jSeparator14);
        jToolBar1.add(jSeparator13);
        jToolBar1.add(jSeparator19);
        jToolBar1.add(jSeparator17);
        jToolBar1.add(jSeparator12);
        jToolBar1.add(jSeparator7);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator20);
        jToolBar1.add(jSeparator22);
        jToolBar1.add(jSeparator21);
        jToolBar1.add(jSeparator25);
        jToolBar1.add(jSeparator26);
        jToolBar1.add(jSeparator27);
        jToolBar1.add(jSeparator23);
        jToolBar1.add(jSeparator24);
        jToolBar1.add(jSeparator35);
        jToolBar1.add(jSeparator34);
        jToolBar1.add(jSeparator28);
        jToolBar1.add(jSeparator30);
        jToolBar1.add(jSeparator31);
        jToolBar1.add(jSeparator32);
        jToolBar1.add(jSeparator33);
        jToolBar1.add(jSeparator29);
        jToolBar1.add(jSeparator1);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.jpg"))); // NOI18N
        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 640, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Planta", "Contratista", "Paciente" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encargado D"));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 180, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrativo", "Asistencial" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createTitledBorder("cargo_egerce"));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 230, 40));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Retirado" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado:"));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/afhce curso activo fijo1.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 640, 370));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.va.validacionCamposNulosB()){
            if(validarEC()){
            guardar();
            code.setText("");
            name.setText("");
            }else{
                JOptionPane.showMessageDialog(rootPane, "ERROR ya esta creado!");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(this.va.validacionCamposNulosB()){
            update();
            this.setVisible(false);
            code.setText("");
            name.setText("");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
        code.setText("");
        name.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
       mayuscula();
    }//GEN-LAST:event_nameKeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
     
        try {
           ResultSet resultado1 = Producto.c.MysqlConsulta("select namedireccion from direccion where codedireccion='" +jTextField2.getText() + "'");
            if (resultado1.next()) {
           jLabel1.setText(resultado1.getString("namedireccion"));
            } else {
                JOptionPane.showMessageDialog(this, "Error este Code no existe");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e);
        }
    
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.poder = ClasArea.are.get("grilladire");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.poder = ClasArea.are.get("grillaarea");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     this.poder = ClasArea.are.get("grildepara");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
             this.poder = ClasArea.are.get("centroospino");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrosResponsables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrosResponsables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrosResponsables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrosResponsables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrosResponsables dialog = new RegistrosResponsables(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator21;
    private javax.swing.JToolBar.Separator jSeparator22;
    private javax.swing.JToolBar.Separator jSeparator23;
    private javax.swing.JToolBar.Separator jSeparator24;
    private javax.swing.JToolBar.Separator jSeparator25;
    private javax.swing.JToolBar.Separator jSeparator26;
    private javax.swing.JToolBar.Separator jSeparator27;
    private javax.swing.JToolBar.Separator jSeparator28;
    private javax.swing.JToolBar.Separator jSeparator29;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator30;
    private javax.swing.JToolBar.Separator jSeparator31;
    private javax.swing.JToolBar.Separator jSeparator32;
    private javax.swing.JToolBar.Separator jSeparator33;
    private javax.swing.JToolBar.Separator jSeparator34;
    private javax.swing.JToolBar.Separator jSeparator35;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

    private boolean validarEC() {
        try {
            ResultSet resultado1 = Producto.c.MysqlConsulta("SELECT * FROM  `responsables` WHERE  `idresponsable` LIKE  '"+code.getText()+"' AND  `codedireccion` LIKE  '"+jTextField2.getText()+"' AND  `codearea` LIKE  '"+jTextField4.getText()+"' AND  `codedepartamento` LIKE  '"+jTextField5.getText()+"' AND  `codecentrodecosto` LIKE  '"+jTextField6.getText()+"'");
            if (resultado1.next()) {
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatosSaldosini.class.getName()).log(Level.SEVERE, null, ex);
        }
    return true;
    }
public void deedfulcode(String codigo){
code.setText(codigo);
}
public void deefaulname(String nombre){
name.setText(nombre);
}
public void deefuljcomb4(String jc4){
jComboBox4.setSelectedItem(jc4);
}
public void deefuljcom1(String jc1){
jComboBox1.setSelectedItem(jc1);
}
public void deefuljcom2(String jc2){
jComboBox2.setSelectedItem(jc2);
}
public void deefuljt2(String jt2){
jTextField2.setText(jt2);
}
public void deefuljl1(String jl1){
jLabel1.setText(jl1);
}
public void deefuljtf4(String jtf4){
jTextField4.setText(jtf4);
}
public void deefuljl2(String jl2){
jLabel2.setText(jl2);
}
public void deefuljtf5(String jtf5){
jTextField5.setText(jtf5);
}
public void deefuljl3(String jl3){
jLabel3.setText(jl3);
}
public void deefuljtf6(String jtf6){
jTextField6.setText(jtf6);
}
public void deefuljl4(String jl4){
jLabel4.setText(jl4);
}
}
