/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package activosfijos;

import java.io.File;
import javax.swing.JOptionPane;
import jxl.Workbook;
import jxl.format.Alignment;
import jxl.format.Border;
import jxl.write.*;

/**
 *
 * @author OSPINO Y ASOCIADO
 */
public class InventarioExportable extends javax.swing.JDialog {
    private final ModelosTabla tm;

    /**
     * Creates new form InventarioExportable
     */
    public InventarioExportable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
               String[] columnas = {"Codigo", "Nombre", "Piso", "IDResponsable", "NombreResponsable", "CodigoContable", "Localizacion", "Serie", "Marca"};
        this.tm = new ModelosTabla(columnas, jTable1);
             jTable1.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {"", "", "", ""},
                {"", "", "", ""},
                {"", "", "", ""}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1050, 330));

        jPanel1.setBackground(new java.awt.Color(255, 250, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/java.jpg"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 120, 40));

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Titulo de informe"));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 50));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1050, 70));

        jPanel2.setBackground(new java.awt.Color(255, 250, 241));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "codigo de la placa"));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
//         if(buscarCB()){
////        this.poder = ActivosFijos.e.get("editaract");
////        JDialog pu = (JDialog) this.poder;
////        pu.setVisible(true);
//        }else{
//            JOptionPane.showMessageDialog(this, "No existe activo");
//        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        ImprimirInformeExcel(jTable1, 2, jTextField2.getText());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
     tm.vaciarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    
//    public boolean buscarCB() {
//       
//        try {
//
//            ResultSet resultado1 = ActivosFijos.c.MysqlConsulta("select * from activosfijos where Codigo='" +jTextField1.getText()+ "'");
//            if (resultado1.next()) {
//                String e[]={ jTextField1.getText(),resultado1.getString("Nombre"),resultado1.getString("Piso"),resultado1.getString("IDResponsable"),resultado1.getString("NombreResponsable"),resultado1.getString("CodigoContable"),resultado1.getString("Localizacion"),resultado1.getString("Serie"),resultado1.getString("Marca")};
//                buscarImagen(resultado1);
//                Editaractivos.pisos.setText(resultado1.getString("Piso"));
//                Editaractivos.centrodecosto.setText(resultado1.getString("CentrodeCosto"));
//                Editaractivos.nombredelcentrocosto.setText(resultado1.getString("NombredeCentrodeCosto"));
//                Editaractivos.oficina.setText(resultado1.getString("Oficina"));
//                Editaractivos.codcontable.setText(resultado1.getString("CodigoContable"));
//                Editaractivos.tipocod.setText(resultado1.getString("TipodeCodigo"));
//                Editaractivos.code.setText(resultado1.getString("Codigo"));
//                Editaractivos.nombre.setText(resultado1.getString("Nombre"));
//                Editaractivos.nomb2.setText(resultado1.getString("Nombre2"));
//                Editaractivos.nombrecontable.setText(resultado1.getString("NombreContable"));
//                Editaractivos.codigodepreciacion.setText(resultado1.getString("CodigoDepreciacion"));
//                Editaractivos.nombredepreciacion.setText(resultado1.getString("NombreDepreciacion"));
//                Editaractivos.codigocontrapartidad.setText(resultado1.getString("CodigoContrapartidaDepre"));
//                Editaractivos.nombrecontrapartidad.setText(resultado1.getString("NombreContrapartidaDepre"));
//                Editaractivos.idproveedor.setText(resultado1.getString("IDProveedor"));
//                Editaractivos.Nombreproveedor.setText(resultado1.getString("NombreProveedor"));
//                Editaractivos.fabricante.setText(resultado1.getString("Fabricante"));
//                Editaractivos.distri.setText(resultado1.getString("Distribuidora"));
//                Editaractivos.idresponsable.setText(resultado1.getString("IDResponsable"));
//                Editaractivos.nombreresponsable.setText(resultado1.getString("NombreResponsable"));
//                Editaractivos.diasdepreciacion.setText(resultado1.getString("DiasdeDepreciacion"));
//                Editaractivos.Tipo.setSelectedItem(resultado1.getString("TiposdeIngreso"));
//                Editaractivos.documentodecompra.setText(resultado1.getString("DocumentodeCompra"));
//                Editaractivos.fechadeadquisicion.setText(resultado1.getString("FechadeAquisicion"));
//                Editaractivos.fechaingreso.setText(resultado1.getString("FechadeIngreso"));
//                Editaractivos.fechadeinst.setText(resultado1.getString("FechadeInst"));
//                Editaractivos.puestaenmarcha.setText(resultado1.getString("PuestaenMarcha"));
//                Editaractivos.fechadebaja.setText(resultado1.getString("FechadeBaja"));
//                Editaractivos.depreciacion.setText(resultado1.getString("Depreciaccion"));
//                Editaractivos.vidadutil.setText(resultado1.getString("Vidautil"));
//                Editaractivos.localizacion.setText(resultado1.getString("Localizacion"));
//                Editaractivos.serie.setText(resultado1.getString("Serie"));
//                Editaractivos.modelo.setText(resultado1.getString("Modelo"));
//                Editaractivos.placa.setText(resultado1.getString("Placa"));
//                Editaractivos.marca.setText(resultado1.getString("Marca"));
//                Editaractivos.estado.setText(resultado1.getString("Estado"));
//                Editaractivos.aseguradora.setText(resultado1.getString("Aseguradora"));
//                Editaractivos.polizaaseguradora.setText(resultado1.getString("PolizaAseguradora"));
//                Editaractivos.vencimiento.setText(resultado1.getString("FechadeVencimientopoli"));
//                Editaractivos.cantidad.setText(resultado1.getString("Cantidad"));
//                Editaractivos.costodeadquisicion.setText(resultado1.getString("CostodeAdquisicion"));
//                Editaractivos.totaladquisicion.setText(resultado1.getString("TotaldeAdquisicion"));
//                Editaractivos.totaldepreciacion.setText(resultado1.getString("totalDepreciaciones"));
//                Editaractivos.totalmantenimiento.setText(resultado1.getString("TotalMantenimiento"));
//                Editaractivos.valoracumulado.setText(resultado1.getString("ValorAcumulado"));
//                Editaractivos.valorizacion.setText(resultado1.getString("Valorizacion"));
//                Editaractivos.fechadevencimientogaran.setText(resultado1.getString("FechadeVencimeintoGaran"));
//                Editaractivos.fechainicialmanteni.setText(resultado1.getString("FechaInicial"));
//                Editaractivos.numerodeseciones.setText(resultado1.getString("numerodeSeciones"));
//                Editaractivos.tiempo.setText(resultado1.getString("Tiempo"));
//                Editaractivos.fechadevencimientomanteni.setText(resultado1.getString("FechadeVencimientoManteni"));
//                Editaractivos.jTextArea1.setText(resultado1.getString("detalle"));
//                tm.ingresarUsuario(e);
//                jTextField1.setText("");
//                return true;
//            }
//            
//
//
//        } catch (Exception e) {
////JOptionPane.showMessageDialog(this,"ERROR"+ e);
//        }
//        return false;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioExportable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioExportable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioExportable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioExportable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                InventarioExportable dialog = new InventarioExportable(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     public void ImprimirInformeExcel(javax.swing.JTable tabla,int ini,String titulo ){
       try
       {
           WritableWorkbook workbook;
           workbook = Workbook.createWorkbook(new File("c:/reportes/"+titulo+".xls"));
           WritableSheet sheet = workbook.createSheet("Factura Ventas", 0);
           //tipo letra
           WritableFont arial10font = new WritableFont(WritableFont.ARIAL, 11,WritableFont.BOLD,true);
           WritableCellFormat arial10format = new WritableCellFormat (arial10font);
 
           WritableCellFormat fCabecera = new WritableCellFormat(arial10font);
//           JOptionPane.showMessageDialog(null,"entre12");
           fCabecera.setAlignment(Alignment.JUSTIFY);
           fCabecera.setVerticalAlignment(VerticalAlignment.CENTRE);
           fCabecera.setBackground(Colour.CORAL);
           fCabecera.setBorder(Border.ALL,BorderLineStyle.THIN);
       
        
             jxl.write.Label label;
           for(int y=0;y<tabla.getColumnCount();y++)
           {
           label= new jxl.write.Label(y, ini,  tabla.getColumnName(y).replace(" ",""),fCabecera);
           sheet.addCell(label);
             sheet.setColumnView(y,tabla.getColumnName(y).length()*180/100);
     
           
           }
  
 
           int i=0,auxi;
           while(i<tabla.getRowCount()){
           auxi=ini+2+i;
           for(int y=0;y<tabla.getColumnCount();y++)
           {
               //JOptionPane.showMessageDialog(null,"entr "+tabla.getValueAt(i, y));
                    if( sheet.getColumnWidth(y)<tabla.getValueAt(i, y).toString().length()*129/100 )
                        sheet.setColumnView(y,tabla.getValueAt(i, y).toString().length()*129/100);
 
            //JOptionPane.showMessageDialog(null,"entr111  "+y);
 
               if(QuitarFormateoEntero(tabla.getValueAt(i, y).toString())==0)
               {
                   if(validar_campos_numerico(tabla.getValueAt(i, y).toString()))
                   {
                       
                   jxl.write.Number number = new jxl.write.Number(y, auxi,QuitarFormateoEntero(tabla.getValueAt(i, y).toString()));
                    sheet.addCell(number);
                   }
                   else
                   {
                   label = new jxl.write.Label(y, auxi,""+tabla.getValueAt(i, y).toString());
                   sheet.addCell(label);
                   }
                   //JOptionPane.showMessageDialog(null,"entr222  "+y);
               }
               else
               {
 
 
                   jxl.write.Number number = new jxl.write.Number(y, auxi,QuitarFormateoEntero(tabla.getValueAt(i, y).toString()));
                    sheet.addCell(number);
 
 
               }
               //JOptionPane.showMessageDialog(null,"fin "+i);
 
           }
 
           i=i+1;
 
           }
 
 
           workbook.write();
           workbook.close();
           JOptionPane.showMessageDialog(null,"Archivo creado correctamente");
 
 
 
       }
       catch(Exception e)
       {
 JOptionPane.showMessageDialog(null,"error de guardar excel formulario:"+ titulo+"  " +e);
       }
   }

public long QuitarFormateoEntero(String x)    
   {
        
    long x1=0;
    if(!x.equals(""))
    {
    x=x.replace(".","");
     x=x.replace("$","");
    try
    {
    x1=Long.parseLong(x);
     return x1;
     } catch (Exception e) {
           // JOptionPane.showMessageDialog(null, "ERROR AL CONVERTIR A ENTERO1 " + e);
        }
    }
 
    return x1;
 
   }

 public boolean validar_campos_numerico(String campo) {
        Long x;
        try {
 
            x = Long.parseLong(campo);
 
 
            return true;
        } catch (Exception e) {
            return false;
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
