/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package menuactivofijo;

import Usuario.EntradadeUsuario1;
import Usuario.Usuarios;
import activosfijos.ActivosFijos;
import activosfijos.InventarioExportable;
import areas.Areas;
import areas.ClasArea;
import areas.GrillaArea;
import deparatementos.Departamentos;
import deparatementos.GrillaDepartamento;
import direcciones.GrillaDirecciones;
import direcciones.RegistroDirecciones;
import grupo.DatosGrupos;
import grupo.Grillagrupo;
import java.sql.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import productos.GrillaProducto;
import productos.RegistroProducto;
import responsables.GrillaResponsable;
import responsables.RegistrosResponsables;
import responsables.centrodecosto;
import saldos.DatosSaldosini;
//import saldos.Espere;
import saldos.GrillaSaldo;
import saldos.Lector;
import saldos.mainFrame;
import traslados.TrasladodeAtivo;

/**
 *
 * @author OSPINO Y ASOCIADO
 */
public class Principal extends javax.swing.JFrame {

    Object poder;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        Usuarios.di.put("EntradadeUsuario", new EntradadeUsuario1(this, true));
        ActivosFijos.e.put("inventario", new InventarioExportable(this, true));
//        ClasArea.are.put("espere", new Espere(this, true));
        ClasArea.are.put("grillaarea", new GrillaArea(this, true));
        ClasArea.are.put("are", new Areas(this, true));
        ClasArea.are.put("grildepara", new GrillaDepartamento(this, true));
        ClasArea.are.put("depar", new Departamentos(this, true));
        ClasArea.are.put("grilladire", new GrillaDirecciones(this, true));
        ClasArea.are.put("regdirecc", new RegistroDirecciones(this, true));
        ClasArea.are.put("grillgrup", new Grillagrupo(this, true));
        ClasArea.are.put("datogrup", new DatosGrupos(this, true));
        ClasArea.are.put("grillaproduc", new GrillaProducto(this, true));
        ClasArea.are.put("produc", new RegistroProducto(this, true));
        ClasArea.are.put("grillarepons", new GrillaResponsable(this, true));
        ClasArea.are.put("respons", new RegistrosResponsables(this, true));
        ClasArea.are.put("trasladoact", new TrasladodeAtivo(this, true));
        ClasArea.are.put("centroospino", new centrodecosto(this, true));
        ClasArea.are.put("h", new Lector(this, true));
        ClasArea.are.put("grisaldo", new GrillaSaldo(this, true));
        ClasArea.are.put("activo", new DatosSaldosini(this, true));
        ClasArea.are.put("mainframex", new mainFrame(this, true));
    }

    public void buscar1() {
        try {
            ResultSet resultado1 = MenuActivoFijo.c.MysqlConsulta("select Nivel from usuario where Nivel='" + jComboBox1.getSelectedItem() + "'");

            if (resultado1.next()) {
                activosfijos.ActivosFijos.main(null);
                JDialog get = ActivosFijos.e.get("Grillact");
                if (get != null) {
                    this.poder = get;
                    get.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "error uste no tiene ningun nivel de autoridad");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/afhce curso activo fijo1.jpg"))); // NOI18N
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1380, 750);

        jPanel1.add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "1", "2", "3" }));

        jMenu4.setText("Datos Generales");

        jMenu1.setText("Entrada a Usuario");

        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu4.add(jMenu1);

        jMenuItem1.setText("Creacion de area");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem4.setText("creacion de Departamento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Creacion de Direcciones");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Creacion de Grupos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Creacion de Productos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Responsables");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);
        jMenu4.add(jSeparator2);

        jMenuItem12.setText("Proveedor");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);
        jMenu4.add(jSeparator1);

        jMenuBar2.add(jMenu4);

        jMenu2.setText("Saldos Activos");

        jMenuItem2.setText("Saldos iniciales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem9.setText("Traslado de Activo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar2.add(jMenu2);

        jMenu5.setText("Lector de Codigo");

        jMenuItem10.setText("Inventario");
        jMenuItem10.setEnabled(false);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1378, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 1377, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 723, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.poder = ClasArea.are.get("activo");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.poder = Usuarios.di.get("EntradadeUsuario");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
        EntradadeUsuario1.pasabordo.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        new Login(this, true).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.poder = ClasArea.are.get("grillaarea");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.poder = ClasArea.are.get("grildepara");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.poder = ClasArea.are.get("grilladire");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.poder = ClasArea.are.get("grillgrup");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.poder = ClasArea.are.get("grillaproduc");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.poder = ClasArea.are.get("grillarepons");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
//       trasladoact
        this.poder = ClasArea.are.get("trasladoact");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.poder = ClasArea.are.get("h");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.poder = ClasArea.are.get("proveed");
        JDialog pu = (JDialog) this.poder;
        pu.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
